[package]
name = "shared_models"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true}
serde_json = {workspace = true}
chrono = { workspace = true}
anyhow = {workspace = true}
log = { workspace = true }
env_logger = { workspace = true }
tokio-postgres = { workspace = true }
sqlx = {workspace = true}
chrono-tz ="0.10.4"
strum_macros= {workspace = true}
strum= {workspace = true}   
async-trait ={ workspace = true}
rdkafka = { workspace = true }