[package]
name = "main_app"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
anyhow ={workspace = true}
deadpool-postgres = { workspace = true }
tokio-postgres = { workspace = true }
log={workspace = true}
env_logger = {workspace = true}
rdkafka = { workspace = true}
dotenvy = {workspace = true}
bytemuck = {workspace = true}
surrealdb = {workspace = true}


data_engine = { path = "../data_engine" }
database_engine ={path = "../database_engine"}
prediction_engine = { path = "../prediction_engine" }
shared_models ={ path = "../shared_models"}
# order_engine = { path = "../order_engine" }
